<?php

namespace AppBundle\Repository\Community;

/**
 * CommunityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $pattern
     * @return array
     */
    public function search($pattern)
    {
        $qb = $this->createQueryBuilder("c")
            ->where("c.name LIKE :pattern")
            ->setParameter("pattern", "%".$pattern."%")
        ;

        return $qb->getQuery()->getResult();
    }
}
