<?php

namespace AppBundle\Repository\Core;

/**
 * ScopeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScopeRepository extends \Doctrine\ORM\EntityRepository
{
}
