<?php

namespace AppBundle\Repository;

/**
 * UserCommunityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCommunityRepository extends \Doctrine\ORM\EntityRepository
{
}
