van_bookmarks:
    path:     /
    defaults: { _controller: VanBookmarkBundle:Default:index }

# Bookmark
van_bookmarks_insert:
    path:     /insert
    defaults: { _controller: VanBookmarkBundle:Bookmark:insert }
van_bookmarks_update:
    path:     /{id}/update
    defaults: { _controller: VanBookmarkBundle:Bookmark:update }
    requirements:
        id: \d+
van_bookmarks_delete:
    path:     /{id}/delete
    defaults: { _controller: VanBookmarkBundle:Bookmark:delete }
    requirements:
        id: \d+

# Category
van_bookmarks_category_insert:
    path:     /category/insert
    defaults: { _controller: VanBookmarkBundle:Category:insert }
van_bookmarks_category_update:
    path:     /category/{id}/update
    defaults: { _controller: VanBookmarkBundle:Category:update }
    requirements:
        id: \d+
van_bookmarks_category_delete:
    path:     /category/{id}/delete
    defaults: { _controller: VanBookmarkBundle:Category:delete }
    requirements:
        id: \d+