app.bookmarks:
    path:     /
    defaults: { _controller: AppBundle:Bookmark/Default:index }

# Bookmark
app.bookmarks.insert:
    path:     /insert
    defaults: { _controller: AppBundle:Bookmark/Bookmark:insert }
app.bookmarks.update:
    path:     /{id}/update
    defaults: { _controller: AppBundle:Bookmark/Bookmark:update }
    requirements:
        id: \d+
app.bookmarks.delete:
    path:     /{id}/delete
    defaults: { _controller: AppBundle:Bookmark/Bookmark:delete }
    requirements:
        id: \d+

# Category
app.bookmarks.category.insert:
    path:     /category/insert
    defaults: { _controller: AppBundle:Bookmark/Category:insert }
app.bookmarks.category.update:
    path:     /category/{id}/update
    defaults: { _controller: AppBundle:Bookmark/Category:update }
    requirements:
        id: \d+
app.bookmarks.category.delete:
    path:     /category/{id}/delete
    defaults: { _controller: AppBundle:Bookmark/Category:delete }
    requirements:
        id: \d+

# Import
app.bookmarks.import:
    path:     /import
    defaults: { _controller: AppBundle:Bookmark/Import:import }