communities_create:
    path:       /create
    defaults:   { _controller: "AppBundle:Community/Default:create" }
communities_show:
    path:       /{id}
    defaults:   { _controller: "AppBundle:Community/Default:show" }
    requirements:
        id: \d+
communities_search:
    path:       /search
    defaults:   { _controller: "AppBundle:Community/Default:search" }
communities_join:
    path:       /{id}/join
    defaults:   { _controller: "AppBundle:Community/Default:join" }
    requirements:
        id: \d+
communities_leave:
    path:       /{id}/leave
    defaults:   { _controller: "AppBundle:Community/Default:leave" }
    requirements:
        id: \d+