app.communities.create:
    path:       /create
    defaults:   { _controller: "AppBundle:Community/Default:create" }
app.communities.show:
    path:       /{id}
    defaults:   { _controller: "AppBundle:Community/Default:show" }
    requirements:
        id: \d+
app.communities.search:
    path:       /search
    defaults:   { _controller: "AppBundle:Community/Default:search" }
app.communities.join:
    path:       /{id}/join
    defaults:   { _controller: "AppBundle:Community/Default:join" }
    requirements:
        id: \d+
app.communities.leave:
    path:       /{id}/leave
    defaults:   { _controller: "AppBundle:Community/Default:leave" }
    requirements:
        id: \d+