app.security.login:
    path:       /login
    defaults:   { _controller: "AppBundle:Security/Default:login" }

app.security.login_check:
    path:       /login_check

logout:
    path:       /logout

app.security.lost_password:
    path:       /lost-password
    defaults:   { _controller: "AppBundle:Security/Default:passwordRetrieval" }

app.security.reset_password:
    path:     /reset-password
    defaults: { _controller: "AppBundle:Security/Default:resetPassword" }