app.user.registration:
    path:     /register
    defaults: { _controller: "AppBundle:User/Registration:index" }

app.user.profile:
    path:     /profile
    defaults: { _controller: "AppBundle:User/Profile:index" }