index:
    path:       /
    defaults:   { _controller: "AppBundle:Default:index" }

communities_create:
    path:       /communities/create
    defaults:   { _controller: "AppBundle:Community:create" }
communities_search:
    path:       /communities/search
    defaults:   { _controller: "AppBundle:Community:search" }
communities_join:
    path:       /communities/{id}/join
    defaults:   { _controller: "AppBundle:Community:join" }
communities_leave:
    path:       /communities/{id}/leave
    defaults:   { _controller: "AppBundle:Community:leave" }