index:
    path:       /
    defaults:   { _controller: "AppBundle:Default:index" }

app.user:
    resource: '@AppBundle/Resources/config/routing/user.yml'

app.security:
    resource: '@AppBundle/Resources/config/routing/security.yml'

app.feed:
    resource: '@AppBundle/Resources/config/routing/feed.yml'

app.bookmark:
    resource: '@AppBundle/Resources/config/routing/bookmark.yml'
    prefix:   'bookmarks'

app.programming:
    resource: '@AppBundle/Resources/config/routing/programming.yml'
    prefix:   'programming'

app.community:
    resource: '@AppBundle/Resources/config/routing/community.yml'
    prefix:   'communities'

app.api_config:
    resource: '@AppBundle/Resources/config/routing/api_config.yml'
    prefix:   'api-configs'
