van_feed_post_save:
    path:     /posts/save
    defaults: { _controller: VanFeedBundle:Post:save }
van_feed_post_like:
    path:     /posts/{id}/like
    defaults: { _controller: VanFeedBundle:Post:like }
    requirements:
        id: \d+

van_feed_comment_save:
    path:     /comments/save
    defaults: { _controller: VanFeedBundle:Comment:save }
van_feed_comment_list_from_post:
    path:     /comments/list-from-post
    defaults: { _controller: VanFeedBundle:Comment:listFromPost }
