<?php

namespace AppBundle\Repository\ApiConfig;

/**
 * StackoverflowConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StackoverflowConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
